/* Vitavolt Global — ANNE CORE | build 2026-09-19-anne-v5-1-inv
 * Path: connect → analyze → task MITOS → VITA deterministic calc → ANNE test → human
 * ANNE does not recompute engineering. VITA is sole math authority.
 * This offline core is the socket for future ANNE AI.
 */
(function (window) {
  'use strict';
  var VERSION = '0.5.1-offline';
  var BUILD = '2026-09-19-anne-v5-1-inv';
  function finite(v) { return Number.isFinite(Number(v)); }
  function present(v) { return v !== undefined && v !== null && String(v).trim() !== '' && !(finite(v) && Number(v) === 0); }
  function unique(list) { return list.filter(function (v, i, a) { return a.indexOf(v) === i; }); }
  function n(v, fb) { var x = Number(v); return Number.isFinite(x) ? x : (fb !== undefined ? fb : 0); }
  function analyzeSystem(raw) { raw=raw||{}; var needs=[]; if(n(raw.roofAreaM2,0)>0||n(raw.landAreaM2,0)>0)needs.push('ges_sizing'); if(n(raw.monthlyConsumptionKwh,0)>0||n(raw.annualConsumptionKwh,0)>0)needs.push('load_match'); if(n(raw.monthlyWaterM3,0)>0||raw.rainwaterSelected||raw.greywaterSelected)needs.push('water'); if(n(raw.nighttimeShare,0)>=0.4||n(raw.peakDemandKw,0)>0)needs.push('bess_screen'); return {domain:'energy_prefeasibility',facilityType:raw.facilityType||raw.tesisTipi||null,city:raw.city||null,needs:needs,requiredEngine:'VITA_ENGINE',mitosTasks:['completeInputs','propose_scenarios'],principle:'First ensure deterministic engine; then MITOS fills inputs; ANNE tests; human approves.'}; }
  function buildAssessment(input,result,mitosMeta){input=input||{};result=result||{};var missing=[],supplied=[],factors=[],evidence=[];function req(key,label){if(present(input[key]))supplied.push(label);else missing.push({key:key,label:label,reason:'required_for_higher_confidence_assessment'});}req('monthlyConsumptionKwh','Aylık elektrik tüketimi');req('city','Tesis şehri');if(present(input.peakDemandKw)){supplied.push('Pik talep');factors.push({id:'peak_demand',label:'Pik talep optimizasyonu',reason:'Pik güç verisi mevcut.'});}if(present(input.nighttimeShare)){supplied.push('Gece tüketim payı');factors.push({id:'load_shift',label:'Yük kaydırma / BESS optimizasyonu',reason:'Gece tüketim profili mevcut.'});}if(present(input.monthlyWaterM3)){supplied.push('Aylık su tüketimi');factors.push({id:'water',label:'Su verimliliği ve yeniden kullanım',reason:'Su tüketim verisi mevcut.'});}if(present(input.facilityType)||present(input.tesisTipi))evidence.push({type:'facility',value:input.facilityType||input.tesisTipi});if(present(input.city))evidence.push({type:'city',value:input.city});var confidence=missing.length===0?'DATA_COMPLETE_FOR_CURRENT_SCOPE':(missing.length<=2?'PARTIAL_DATA':'LIMITED_DATA');return {status:'ANNE_VITA_VALIDATED',version:VERSION,build:BUILD,confidence:confidence,facility:{type:input.facilityType||input.tesisTipi||null,city:input.city||null},missing:missing,supplied:supplied,factors:factors,evidence:evidence,mitos:mitosMeta||null,principle:'VITA is sole deterministic calculation engine'};}
  function test(result,input){var checks=[];function add(id,ok,detail){checks.push({id:id,ok:!!ok,detail:detail||''});}if(!result||!result.solar||!result.pricing)return {ok:false,status:'INCOMPLETE_RESULT',checks:[{id:'structure',ok:false,detail:'missing solar/pricing'}]};var s=result.solar,p=result.pricing,pw=n(result.assumptions&&result.assumptions.panelPowerWp,620),expectedDc=Math.round(n(s.panelCount)*pw/1000*100)/100;add('PANEL_KWP',Math.abs(n(s.dcCapacityKwp)-expectedDc)<0.05,'dc='+s.dcCapacityKwp+' expected~'+expectedDc);var factor=n(result.assumptions&&result.assumptions.co2FactorKgPerKwh,0.42),co2=Math.round(n(s.annualProductionKwh)*factor);add('CO2',Math.abs(n(s.co2ReductionKg)-co2)<=1,'co2='+s.co2ReductionKg+' expected='+co2);if(p.battery&&n(p.battery.requestedCapacityKwh)>0){var units=Math.ceil(n(p.battery.requestedCapacityKwh)/2.4);add('BESS_MODULES',n(p.battery.batteryModuleCount)===units,'modules='+p.battery.batteryModuleCount+' expected='+units);}else add('BESS_MODULES',true,'no BESS request');if(p.inverter&&n(s.dcCapacityKwp)>0){var dc=n(s.dcCapacityKwp),ac=n(p.inverter.powerKw)*n(p.inverter.count,1),target=n(p.inverter.targetAcDcRatio,0.80),ratio=dc>0?ac/dc:0,withinDc=ac<=dc+0.05&&ac>0,preferred=ac>=dc*target-0.05,residentialOk=withinDc&&ratio>=0.65,fallback=p.inverter.sizingFallback===true;add('INVERTER_DC_AC_RULE',preferred||fallback||residentialOk,'dc='+dc+' ac='+ac+' ratio='+Math.round(ratio*100)/100+' target='+target);}if(input&&n(input.roofAreaM2,0)>0)add('ROOF_LOSS_TAG',input.roofOrientationLossPct==null||n(input.roofOrientationLossPct)===20,'roofLossPct='+input.roofOrientationLossPct);if(result.water&&result.water.rainfall&&result.water.rainfall.selected){var hasWaterBom=(p.bom||[]).some(function(x){return x.category==='WATER';});add('WATER_BOM',hasWaterBom,hasWaterBom?'WATER lines present':'missing WATER BOM');}add('VITA_VALIDATION',!!(result.validation&&result.validation.ok),result.validation&&result.validation.ok?'OK':'CHECK');var failed=checks.filter(function(c){return !c.ok;});return {ok:failed.length===0,status:failed.length===0?'PASSED':'FAILED',checks:checks,failedCount:failed.length,mustNot:'recompute_or_override_vita_engineering'};}
  function ensureMitos(){if(window.MitosCore&&typeof window.MitosCore.completeInputs==='function')return Promise.resolve();return new Promise(function(resolve,reject){var sc=document.createElement('script');sc.src='js/mitos-core.js?v=2026-09-17-mitos-v3';sc.onload=function(){resolve();};sc.onerror=function(){reject(new Error('MITOS yüklenemedi'));};document.head.appendChild(sc);});}
  function runPipeline(input,options){input=input||{};options=options||{};var analysis=analyzeSystem(input);var pack=null,mitosProposal=null,evaluated=[];if(window.MitosCore&&typeof window.MitosCore.completeInputs==='function'){pack=window.MitosCore.completeInputs(input);if(pack&&pack.input){input=Object.assign({},input,pack.input);}}if(window.MitosCore&&typeof window.MitosCore.proposeScenarios==='function'){try{mitosProposal=window.MitosCore.proposeScenarios(input);evaluated=mitosProposal&&mitosProposal.scenarios||[];}catch(e){}}if(!window.VitaEngine||typeof window.VitaEngine.calculate!=='function')throw new Error('VITA Engine required');var result=window.VitaEngine.calculate(input);var anneTest=test(result,input);var assessment=buildAssessment(input,result,{pack:pack,proposal:mitosProposal});result.anne=Object.assign({},assessment,{test:anneTest});result.contracts={vita:{role:'sole_deterministic_calculation_engine',mustNot:'be_replaced_by_anne_or_mitos_math'}};result.mitos={status:mitosProposal?'INPUTS_COMPLETED_AND_SCENARIOS_EVALUATED':'INPUTS_ONLY',complete:pack,proposal:mitosProposal,evaluatedScenarioCount:evaluated.length};result.flow=['SYSTEM_ANALYZE','MITOS_COMPLETE_INPUTS','VITA_DETERMINISTIC_CALC','ANNE_DETERMINISTIC_TEST','HUMAN_APPROVAL'];if(!anneTest.ok)result.anne.status='ANNE_TEST_FAILED';return result;}
  function assess(input,options){return runPipeline(input,options);}
  function proposeScenario(input,objective){return {status:'PROPOSAL_ONLY',objective:objective||'optimize_total_project_outcome',source:'ANNE_CORE',input:input||{},nextStep:'MITOS completeInputs → VITA calculate → ANNE test → Human',humanApprovalRequired:true};}
  function outputPlan(result,audience){return {audience:audience||'human',status:(result&&result.anne&&result.anne.status)||'UNKNOWN',humanApprovalRequired:true,note:'Engineering numbers from VITA only'};}
  window.AnneCore={version:VERSION,build:BUILD,analyzeSystem:analyzeSystem,buildAssessment:buildAssessment,test:test,ensureMitos:ensureMitos,runPipeline:runPipeline,assess:assess,proposeScenario:proposeScenario,outputPlan:outputPlan};
})(typeof window!=='undefined'?window:this);
